### PR TITLE
fix: Catch errors from async handlers.

### LINKED ISSUE #87: Catch errors from async handlers.
About LambdaWrapper - I have been trying to use `1.1.0` and I have the following issue:

https://github.com/comicrelief/lambda-wrapper/blob/master/src/Wrapper/LambdaWrapper.js#L34

This line assumes that the error is going to be evaluated sync. However, errors can very well be async.

I have two solutions in mind
1. Check if the output of handler is a Promise. If it is a promise, then it and catch the error in the .catch block
2. Convert the instance function into async

The first solution (promises) have larger compatibility as we won't transform the return value of every function into a promise. 
However: it's using promises and it's clunky.

The second solution is cleaner, however every single return value returned by instance is going to be a Promise (and that's a breaking change)

I will put a MR for the Promise solution for now as I need the lib to work with async handlers, but I think it's worth considering a breaking change? It's fair to assume that implementing libraries should make use of async functions anyway

### PR DESCRIPTION
**Pull request by dipasqualew**
Closes #87 

Implements the Promise solution.

### CODE REVIEW

File: src/Wrapper/LambdaWrapper.js [hunk 1]
```diff
@@ -31,23 +49,15 @@ export default ((configuration, handler) => {
...
+      let outcome = handler.call(instance, di, request, callback);
 
-      const responseDetails = {
-        body: error.body || {},
-        code: error.code || 500,
-        message: 'unknown error',
-      };
+      if (outcome instanceof Promise) {
+        outcome = outcome.catch(handleError);
+      }
```
Comment (tomisaacmarshall) [inline src/Wrapper/LambdaWrapper.js:56]: Looks weird to me that we call the handler, which might end up in a rejected promise, before chaining the `.catch` ... but guessing it's no different from doing `handler().catch()` if we already knew the handler was a promise?

Comment (dipasqualew) [reply src/Wrapper/LambdaWrapper.js:56]: Yeah there is no way to know whether the handler is an async function before calling it so if we are handling a normal function chaining `.catch` would throw

Comment (tomisaacmarshall) [reply src/Wrapper/LambdaWrapper.js:56]: Cool. Apparently `handler.constructor.name === 'AsyncFunction` if it's async

Comment (dipasqualew) [reply src/Wrapper/LambdaWrapper.js:56]: I didn't know that! Cheers

I guess that armed with this knowledge we could wrap it in a if/else and do the try/catch block in one branch and the promise catch in the other. But to be honest I think it would be even uglier! 😄
